version = 0.1
[default]
[default.pipeline_bootstrap]
[default.pipeline_bootstrap.parameters]
pipeline_user = "arn:aws:iam::009502615868:user/aws-sam-cli-managed-dev-pipeline-reso-PipelineUser-QG0SLACGC652"
permissions_provider = "AWS IAM"

[dev]
[dev.pipeline_bootstrap]
[dev.pipeline_bootstrap.parameters]
pipeline_execution_role = "arn:aws:iam::009502615868:role/aws-sam-cli-managed-dev-pipe-PipelineExecutionRole-LXRSPBS6NJMX"
cloudformation_execution_role = "arn:aws:iam::009502615868:role/aws-sam-cli-managed-dev-p-CloudFormationExecutionR-1AIWE373741D0"
artifacts_bucket = "aws-sam-cli-managed-dev-pipeline-artifactsbucket-9e138h11pi0f"
image_repository = ""
region = "us-east-1"

[prod]
[prod.pipeline_bootstrap]
[prod.pipeline_bootstrap.parameters]
pipeline_execution_role = "arn:aws:iam::577021173141:role/aws-sam-cli-managed-prod-pip-PipelineExecutionRole-1COVIB8WNOBXE"
cloudformation_execution_role = "arn:aws:iam::577021173141:role/aws-sam-cli-managed-prod-CloudFormationExecutionR-12XHAWAOPZ1X9"
artifacts_bucket = "aws-sam-cli-managed-prod-pipeline-artifactsbucket-1s6us720dt8dr"
image_repository = ""
region = "us-east-1"
